### ISSUE TITLE
Change in SolarEdge Modbus Multi Device v2.3.0 requires rewrite in energy_stats.yaml

### ISSUE THREAD

**Issue by jamescastle** [ryanm101/hasolarcfg#6]
As of update 2.3.0 of the SolarEdge Modbus Multi Device, they change the return value for the sensor.solaredge_b1_status. Now they use text values instead of numbers. Here the block with required changes:
`
        
    # Battery Stats    
    - name: "Solaredge B1 Status Text"
      unique_id: solaredge_b1_status_text
      state: >
        {% set status = states('sensor.solaredge_b1_status') %}
        {% if status == 'B_STATUS_OFF' %}Off
        {% elif status == 'B_STATUS_STANDBY' %}Standby
        {% elif status == 'B_STATUS_INIT' %}Initialise
        {% elif status == 'B_STATUS_CHARGE' %}Charging
        {% elif status == 'B_STATUS_DISCHARGE' %}Discharging
        {% elif status == 'B_STATUS_FAULT' %}Fault
        {% elif status == 'B_STATUS_PRESERVE_CHARGE' %}Preserve Charge
        {% elif status == 'B_STATUS_IDLE' %}Idle
        {% elif status == 'B_STATUS_POWER_SAVING' %}Power saving
        {% else %}{{ states('sensor.solaredge_b1_status') }}
        {% endif %}`

**Comment by Daverover66** [comment]
I picked that up too.  Battery status actually goes from 1 to 10 though and that's only 9. I've also yet to see any official SE documentation showing what each status means.  Also, for anyone who monitors them, there has been a similar change to the way inverter status is shown.

**Comment by jamescastle** [comment]
It should be 1 to 10 (0 is "off"), yes. But I took those entries from their Github page and those are all values they use. Values '8' and '9' are "missing" (or not used).

Edit:
https://github.com/WillCodeForCats/solaredge-modbus-multi/blob/main/custom_components/solaredge_modbus_multi/const.py

**Comment by ryanm101** [comment]
I'll look tonight when home
