### ISSUE TITLE
No time for "battery time to full" displayed

### ISSUE THREAD

**Issue by jamescastle** [ryanm101/hasolarcfg#7]
The value of battery_time_to_full always was "not available", whereas battery_time_to_empty was. The difference (and solution) was to erase the line "unit_of_measurement: "hours"" completely.
After that, all values are displayed like they should be.

I also tried to change it to just "h", as it was mentioned here [https://github.com/home-assistant/core/blob/d7ac4bd65379e11461c7ce0893d3533d8d8b8cbf/homeassistant/const.py#L384](url), but it didn't work either.

**Comment by ryanm101** [comment]
works fine on my install, using the same code though im on v2.2.14

**Comment by jamescastle** [comment]
It was displaying the time correctly, after your big change. But it then stopped displaying the time at all (not available) and now I "fixed" it here with removing mentioned line. This problem existed prior before the upgrade of the Modbus integration.
Honestly, I can't tell, what causes this, but this was the only difference between the (always) working "battery_time_to_empty" and the not working "battery_time_to_full". And after removing this line, it displays the time flawlessly.

Edit:
HA 2023.5.2, Superv.: 2023.04.1 and OS 10.1 (those are the versions I have right now)

**Comment by ryanm101** [comment]
<img width="553" alt="Screenshot 2023-05-15 at 09 30 02" src="https://github.com/ryanm101/hasolarcfg/assets/5185337/4a3f2b7d-b963-4cc6-aaad-c2983a69651e">
<img width="552" alt="Screenshot 2023-05-15 at 09 29 53" src="https://github.com/ryanm101/hasolarcfg/assets/5185337/cffc293b-c140-4cb8-bf39-dfa2110b6996">


Interestingly I get two different 'popups' for them in the UI
